spring:
  application:
    name: workspace

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:postgresql://localhost:5438/appdb
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 6MB

  mail:
    host: smtp.zoho.eu
    port: 587
    username: ${MAIL_USERNAME}  # твой gmail адрес
    password: ${MAIL_PASSWORD}  # App Password, не обычный пароль!
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true

  web:
    resources:
      static-locations:
        - file:/var/app/
        - classpath:/static/

app:
  jwt:
    secret: ${APP_JWT_SECRET}   # минимум 32 байта в base64
    expiration-ms: 86400000   # 24 часа

  admin:
    username: admin
    password-hash: ${APP_ADMIN_PASSWORD_HASH}

  avatar:
    storage-path: /var/app/uploads/avatars
    max-file-size-bytes: 5242880


springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

