spring.application.name=workspace

spring.datasource.url=jdbc:postgresql://localhost:5438/appdb
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring:
    servlet:
        multipart:
            enabled: true
            max-file-size: 4MB
            max-request-size: 4MB